2020-10-18 15:03:50,419 - INFO - {'clientName': "<FileStorage: 'user_name' (None)>", 'clientId': "<FileStorage: 'user_id' (None)>", 'filename': '0c9b2272-2632-4d96-974b-81d81202175e', 'activity': 1, 'created': datetime.datetime(2020, 10, 18, 15, 3, 50, 418093), 'file_metadata': "<FileStorage: 'metadata' (None)>", 'gridFs_id': ObjectId('5f8c5956c9c1592f7f856af1')}
2020-10-18 15:03:50,444 - INFO - {'clientName': "<FileStorage: 'user_name' (None)>", 'clientId': "<FileStorage: 'user_id' (None)>", 'filename': '0c9b2272-2632-4d96-974b-81d81202175e', 'activity': 1, 'created': datetime.datetime(2020, 10, 18, 15, 3, 50, 418093), 'file_metadata': "<FileStorage: 'metadata' (None)>", 'gridFs_id': ObjectId('5f8c5956c9c1592f7f856af1')}
2020-10-18 15:03:50,449 - INFO - MongoDB - Inserted to the MongoDB
2020-10-18 15:03:50,449 - INFO - File Uploaded Successfully
2020-10-18 15:03:50,466 - INFO - Consumer Task Completed
2020-10-18 15:09:34,069 - INFO - Obj received from rabbitMq
2020-10-18 15:09:34,070 - INFO - {'id': 'cc587858-3e01-4ae6-9fe2-2e630da29365', 'file_name': 'db72e31e-cc7f-4ae0-9e52-d741a326ba28', 'file_cache_key': 'file:db72e31e-cc7f-4ae0-9e52-d741a326ba28', 'file_metadata': "<FileStorage: 'metadata' (None)>", 'user_id': "<FileStorage: 'user_id' (None)>", 'user_name': "<FileStorage: 'user_name' (None)>", 'event_timestamp': 1603033774.0658438}
2020-10-18 15:09:34,924 - INFO - AWS S3 - Upload successful
2020-10-18 15:09:34,929 - INFO - MongoDB GridFs - Inserted to the MongoDB GridFs
2020-10-18 15:09:34,930 - INFO - Dict to be stored in MongoDb
2020-10-18 15:09:34,931 - INFO - {'clientName': "<FileStorage: 'user_name' (None)>", 'clientId': "<FileStorage: 'user_id' (None)>", 'filename': 'db72e31e-cc7f-4ae0-9e52-d741a326ba28', 'activity': 1, 'created': datetime.datetime(2020, 10, 18, 15, 9, 34, 930229), 'file_metadata': "<FileStorage: 'metadata' (None)>", 'gridFs_id': ObjectId('5f8c5aaec9c1592f7f856af4')}
2020-10-18 15:09:34,932 - INFO - {'clientName': "<FileStorage: 'user_name' (None)>", 'clientId': "<FileStorage: 'user_id' (None)>", 'filename': 'db72e31e-cc7f-4ae0-9e52-d741a326ba28', 'activity': 1, 'created': datetime.datetime(2020, 10, 18, 15, 9, 34, 930229), 'file_metadata': "<FileStorage: 'metadata' (None)>", 'gridFs_id': ObjectId('5f8c5aaec9c1592f7f856af4')}
2020-10-18 15:09:34,935 - INFO - MongoDB - Inserted to the MongoDB
2020-10-18 15:09:34,936 - INFO - File Uploaded Successfully
2020-10-18 15:09:34,951 - INFO - Consumer Task Completed
2020-10-18 15:13:01,650 - INFO - Aborting transport connection: state=1; <socket.socket fd=12, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.18.0.7', 42964), raddr=('172.18.0.12', 5672)>
2020-10-18 15:13:01,748 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=12, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.18.0.7', 42964)>
2020-10-18 15:13:01,758 - INFO - Deactivating transport: state=1; <socket.socket fd=12, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.18.0.7', 42964)>
2020-10-18 15:13:01,765 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2020-10-18 15:13:01,772 - INFO - Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2020-10-18 15:13:01,776 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=12, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.18.0.7', 42964)>
2020-10-18 15:13:01,788 - ERROR - Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2020-10-20 13:54:46,801 - INFO - RabbitMq thread started app starting
2020-10-20 13:54:46,805 - INFO - Pika version 1.1.0 connecting to ('172.18.0.5', 5672)
2020-10-20 13:54:46,820 - ERROR - Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.18.0.11', 49866)>; error=111 (Connection refused)
2020-10-20 13:54:46,823 - ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.18.0.5', 5672))
2020-10-20 13:54:46,822 - INFO -  * Running on http://0.0.0.0:4500/ (Press CTRL+C to quit)
2020-10-20 13:54:46,834 - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2020-10-20 13:54:46,853 - ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.
2020-10-20 13:54:46,855 - ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2020-10-20 13:54:46,857 - ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2020-10-20 13:54:46,870 - ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
